Repository opendistro-for-elasticsearch/k-NN, pull requests merged in 2020-09, with the labels that each got.

#205 Add default index settings when parsing index
  src/main/java/com/amazon/opendistroforelasticsearch/knn/index/KNNSettings.java
  src/main/java/com/amazon/opendistroforelasticsearch/knn/index/KNNVectorFieldMapper.java
  src/test/java/com/amazon/opendistroforelasticsearch/knn/index/KNNVectorFieldMapperTests.java
Labels: Bug Fixes

#209 Update default variable settings name
  src/main/java/com/amazon/opendistroforelasticsearch/knn/index/KNNSettings.java
  src/main/java/com/amazon/opendistroforelasticsearch/knn/index/KNNVectorFieldMapper.java
  src/test/java/com/amazon/opendistroforelasticsearch/knn/index/KNNVectorFieldMapperTests.java
Labels: Refactoring

#212 NPE in force merge when non knn doc gets updated to knn doc across segments
  src/main/java/com/amazon/opendistroforelasticsearch/knn/index/codec/KNN80Codec/KNN80DocValuesReader.java
  src/test/java/com/amazon/opendistroforelasticsearch/knn/KNNRestTestCase.java
  src/test/java/com/amazon/opendistroforelasticsearch/knn/index/KNNMapperSearcherIT.java
Labels: Bug Fixes

#215 Fix casting issue with cache expiration
  src/main/java/com/amazon/opendistroforelasticsearch/knn/index/KNNIndexCache.java
  src/test/java/com/amazon/opendistroforelasticsearch/knn/index/KNNESSettingsTestIT.java
Labels: Bug Fixes

#217 Upgrade Elasticsearch to 7.9.1 and ODFE to 1.10.1
  build.gradle
  jni/CMakeLists.txt
Labels: Maintenance

#218 Add release notes for 1.10.1
  release-notes/opendistro-for-elasticsearch-knn.release-notes-1.10.1.0.md
Labels: Documentation

#228 Add existsQuery method implementation to KNNVectorFieldType
  src/main/java/com/amazon/opendistroforelasticsearch/knn/index/KNNVectorFieldMapper.java
  src/test/java/com/amazon/opendistroforelasticsearch/knn/KNNRestTestCase.java
  src/test/java/com/amazon/opendistroforelasticsearch/knn/index/KNNESIT.java
Labels: Enhancements

#232 Change "space" parameter to "space_type" for custom scoring
  src/main/java/com/amazon/opendistroforelasticsearch/knn/plugin/script/KNNVectorScoreScript.java
  src/test/java/com/amazon/opendistroforelasticsearch/knn/plugin/scripts/KNNScriptScoringIT.java
Labels: Enhancements

#233 Add stats for custom scoring feature
  README.md
  src/main/java/com/amazon/opendistroforelasticsearch/knn/plugin/script/KNNScoringScriptEngine.java
  src/main/java/com/amazon/opendistroforelasticsearch/knn/plugin/script/KNNVectorScoreScript.java
  src/main/java/com/amazon/opendistroforelasticsearch/knn/plugin/stats/KNNCounter.java
  src/main/java/com/amazon/opendistroforelasticsearch/knn/plugin/stats/KNNStatsConfig.java
  src/main/java/com/amazon/opendistroforelasticsearch/knn/plugin/stats/StatNames.java
  src/test/java/com/amazon/opendistroforelasticsearch/knn/plugin/action/RestKNNStatsHandlerIT.java
Labels: Enhancements

#235 Fix script statistics flaky test case
  src/test/java/com/amazon/opendistroforelasticsearch/knn/KNNRestTestCase.java
  src/test/java/com/amazon/opendistroforelasticsearch/knn/plugin/action/RestKNNStatsHandlerIT.java
Labels: Bug Fixes
