Repository opendistro-for-elasticsearch/k-NN, pull requests merged in 2021-02, with the labels that each got.

#312 Upgrade odfe version to 1.13.0
  build.gradle
  gradle.properties
  jni/CMakeLists.txt
Labels: Infrastructure

#301 Change CD workflow to use new staging bucket for artifacts
  .github/workflows/CD.yml
Labels: Infrastructure

#313 Add release notes for 1.13.0
  release-notes/opendistro-for-elasticsearch-knn.release-notes-1.13.0.0.md
Labels: Maintenance

#310 Added L1 index and scoring
  src/main/java/com/amazon/opendistroforelasticsearch/knn/index/SpaceTypes.java
  src/main/java/com/amazon/opendistroforelasticsearch/knn/index/util/KNNConstants.java
  src/main/java/com/amazon/opendistroforelasticsearch/knn/plugin/script/KNNScoringSpace.java
  src/main/java/com/amazon/opendistroforelasticsearch/knn/plugin/script/KNNScoringSpaceFactory.java
  src/main/java/com/amazon/opendistroforelasticsearch/knn/plugin/script/KNNScoringUtil.java
  src/main/resources/com/amazon/opendistroforelasticsearch/knn/plugin/script/knn_whitelist.txt
  src/test/java/com/amazon/opendistroforelasticsearch/knn/index/KNNJNITests.java
  src/test/java/com/amazon/opendistroforelasticsearch/knn/plugin/script/KNNScriptScoringIT.java
  src/test/java/com/amazon/opendistroforelasticsearch/knn/plugin/script/PainlessScriptScoringIT.java
Labels: Features

#316 Change l1 name to l1Norm for painless
  src/main/java/com/amazon/opendistroforelasticsearch/knn/plugin/script/KNNScoringSpace.java
  src/main/java/com/amazon/opendistroforelasticsearch/knn/plugin/script/KNNScoringUtil.java
  src/main/resources/com/amazon/opendistroforelasticsearch/knn/plugin/script/knn_whitelist.txt
  src/test/java/com/amazon/opendistroforelasticsearch/knn/plugin/script/PainlessScriptScoringIT.java
Labels: Refactoring

#317 Change mode for jni arrays release to prevent unnecessary copy backs
  jni/src/com_amazon_opendistroforelasticsearch_knn_index_v2011_KNNIndex.cpp
Labels: Enhancements

#315 Add support for L-inf distance in AKNN, custom scoring and painless scripting
  src/main/java/com/amazon/opendistroforelasticsearch/knn/index/SpaceTypes.java
  src/main/java/com/amazon/opendistroforelasticsearch/knn/index/util/KNNConstants.java
  src/main/java/com/amazon/opendistroforelasticsearch/knn/plugin/script/KNNScoringSpace.java
  src/main/java/com/amazon/opendistroforelasticsearch/knn/plugin/script/KNNScoringSpaceFactory.java
  src/main/java/com/amazon/opendistroforelasticsearch/knn/plugin/script/KNNScoringUtil.java
  src/main/resources/com/amazon/opendistroforelasticsearch/knn/plugin/script/knn_whitelist.txt
  src/test/java/com/amazon/opendistroforelasticsearch/knn/index/KNNJNITests.java
  src/test/java/com/amazon/opendistroforelasticsearch/knn/plugin/script/KNNScriptScoringIT.java
  src/test/java/com/amazon/opendistroforelasticsearch/knn/plugin/script/PainlessScriptScoringIT.java
Labels: Features

#318 Update minimum score to 0.
  src/main/java/com/amazon/opendistroforelasticsearch/knn/plugin/script/KNNScoreScript.java
  src/main/java/com/amazon/opendistroforelasticsearch/knn/plugin/script/KNNScoringUtil.java
  src/test/java/com/amazon/opendistroforelasticsearch/knn/plugin/script/KNNScoringUtilTests.java
Labels: Enhancements

#320 Move constants out of index folder into common
  src/main/java/com/amazon/opendistroforelasticsearch/knn/common/KNNConstants.java
  src/main/java/com/amazon/opendistroforelasticsearch/knn/index/KNNVectorFieldMapper.java
  src/main/java/com/amazon/opendistroforelasticsearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumer.java
  src/main/java/com/amazon/opendistroforelasticsearch/knn/plugin/script/KNNScoringSpaceFactory.java
  src/test/java/com/amazon/opendistroforelasticsearch/knn/index/KNNVectorFieldMapperTests.java
  src/test/java/com/amazon/opendistroforelasticsearch/knn/plugin/action/RestKNNStatsHandlerIT.java
  src/test/java/com/amazon/opendistroforelasticsearch/knn/plugin/script/KNNScoringSpaceFactoryTests.java
  src/test/java/com/amazon/opendistroforelasticsearch/knn/plugin/script/KNNScriptScoringIT.java
Labels: Refactoring

#323 Update master to main
  .github/workflows/CI.yml
  .github/workflows/draft-release-notes-workflow.yml
  .github/workflows/test-workflow.yml
  CONTRIBUTING.md
  README.md
  release-notes/opendistro-elasticsearch-knn.release-notes-1.7.0.md
  src/main/java/com/amazon/opendistroforelasticsearch/knn/index/KNNCircuitBreaker.java
Labels: Documentation

#311 Documentation refactor
  PerformanceTuning.md
  README.md
Labels: Documentation

#326 Change docs button in README.md
  README.md
Labels: Documentation

#324 Add support for inner product in ANN, custom scoring and painless
  src/main/java/com/amazon/opendistroforelasticsearch/knn/common/KNNConstants.java
  src/main/java/com/amazon/opendistroforelasticsearch/knn/index/KNNWeight.java
  src/main/java/com/amazon/opendistroforelasticsearch/knn/index/SpaceTypes.java
  src/main/java/com/amazon/opendistroforelasticsearch/knn/plugin/script/KNNScoringSpace.java
  src/main/java/com/amazon/opendistroforelasticsearch/knn/plugin/script/KNNScoringSpaceFactory.java
  src/main/java/com/amazon/opendistroforelasticsearch/knn/plugin/script/KNNScoringUtil.java
  src/main/resources/com/amazon/opendistroforelasticsearch/knn/plugin/script/knn_whitelist.txt
  src/test/java/com/amazon/opendistroforelasticsearch/knn/index/KNNJNITests.java
  src/test/java/com/amazon/opendistroforelasticsearch/knn/plugin/script/KNNScoringSpaceFactoryTests.java
  src/test/java/com/amazon/opendistroforelasticsearch/knn/plugin/script/KNNScoringSpaceTests.java
  src/test/java/com/amazon/opendistroforelasticsearch/knn/plugin/script/KNNScriptScoringIT.java
  src/test/java/com/amazon/opendistroforelasticsearch/knn/plugin/script/PainlessScriptScoringIT.java
Labels: Features
